// stopLocation.js
export const stopLocation = {
  data: [
    {
      id: 123,
      type: "restaurant",
      name: "Chipotle",
      parkCount: 3,
      addedTime: 7,
      location: [40.7128, -74.006],
      address: "123 Main St, Cityville, USA",
    },
    {
      id: 130,
      type: "gas station",
      name: "Exxon",
      parkCount: 2,
      addedTime: 6,
      location: [34.0522, -118.2437],
      address: "501 Elm St, Petroville, USA",
    },
    {
      id: 124,
      type: "cafe",
      name: "Starbucks",
      parkCount: 2,
      addedTime: 5,
      location: [34.0522, -118.2437],
      address: "456 Elm St, Townsville, USA",
    },
    {
      id: 133,
      type: "gas station",
      name: "Sunoco",
      parkCount: 2,
      addedTime: 6,
      location: [40.7128, -74.006],
      address: "804 Cedar St, Powerburg, USA",
    },
    {
      id: 125,
      type: "bar",
      name: "The Pub",
      parkCount: 5,
      addedTime: 10,
      location: [51.5074, -0.1278],
      address: "789 Oak St, Villageton, USA",
    },
    {
      id: 132,
      type: "gas station",
      name: "BP",
      parkCount: 1,
      addedTime: 3,
      location: [37.7749, -122.4194],
      address: "703 Maple St, Energyville, USA",
    },
    {
      id: 126,
      type: "fast food",
      name: "McDonald's",
      parkCount: 1,
      addedTime: 3,
      location: [37.7749, -122.4194],
      address: "101 Pine St, Hamletville, USA",
    },
    {
      id: 127,
      type: "pizza",
      name: "Pizza Hut",
      parkCount: 4,
      addedTime: 8,
      location: [45.4215, -75.6993],
      address: "202 Maple St, Countryside, USA",
    },
    {
      id: 128,
      type: "diner",
      name: "Denny's",
      parkCount: 2,
      addedTime: 6,
      location: [40.7128, -74.006],
      address: "303 Cedar St, Riverside, USA",
    },
    {
      id: 129,
      type: "gas station",
      name: "Shell",
      parkCount: 3,
      addedTime: 5,
      location: [38.9072, -77.0375],
      address: "405 Oak St, Metroville, USA",
    },
    {
      id: 131,
      type: "gas station",
      name: "Chevron",
      parkCount: 4,
      addedTime: 8,
      location: [41.8781, -87.6298],
      address: "602 Pine St, Fuelton, USA",
    },
  ],
};
